image: gitpod/workspace-full

tasks:
  - before: npm install -g https://github.com/selmer512/mira-cli
    init: mira create birth
    command: mira start

ports:
  - port: 1337
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true
